package View;

import Utills.Validation;
import Model.ContractModel;
import Model.CustomerModel;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KhoiLeQuoc
 */
public class EditCustomer extends javax.swing.JFrame {

    /**
     * Creates new form Edit Customer
     */
    public EditCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
        Image favicon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/favicon.png"));
        this.setIconImage(favicon);
        showInfo();

    }

    /**
     * show info to field
     */
    public void showInfo() {
        try {
            customerModel = new CustomerModel();
        } catch (Exception ex) {
            Logger.getLogger(EditCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < customerModel.getList().size(); i++) {
            if (customerModel.getList().get(i).getCustomerId() == Home.customerSelected) {
                txtCustomerId.setText(Integer.toString(customerModel.getList().get(i).getCustomerId()));
                txtCustomerName.setText(customerModel.getList().get(i).getCustomerName());
                txtSocialId.setText(customerModel.getList().get(i).getSocialId());
                txtDateRange.setText(customerModel.getList().get(i).getDateRange());
                txtRegisteredDate.setText(customerModel.getList().get(i).getRegisteredPlace());
                txtPhoneNumber.setText(customerModel.getList().get(i).getPhoneNumber());
                txtAddress.setText(customerModel.getList().get(i).getAddress());
                if (customerModel.getList().get(i).getIsActive() != 0) {
                    chkDeactive.setSelected(true);
                }
                if (customerModel.getList().get(i).getCustomerImage().endsWith("0")) {
                    chkCustomerImage.setSelected(true);
                }
            }
        }
    }

    private void updateCustomer() {
        int isActive = 0;
        if (chkDeactive.isSelected()) {
            isActive = 1;
        }
        String haveImage = "1";
        if (chkCustomerImage.isSelected()) {
            haveImage = "0";
        }
        try {
            customerModel.updatePhoneAddress(Home.customerSelected, txtPhoneNumber.getText(), txtAddress.getText(), isActive, haveImage);
        } catch (SQLException ex) {
            Logger.getLogger(EditCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void callHome() {
        Home home = new Home();
        home.cardLayout.show(home.pnlRight, "pnlCardCustomer");
        home.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkDeactive = new javax.swing.JCheckBox();
        chkCustomerImage = new javax.swing.JCheckBox();
        txtPhoneNumber = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblRegisteredDate = new javax.swing.JLabel();
        txtRegisteredDate = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDateRange = new javax.swing.JLabel();
        txtDateRange = new javax.swing.JLabel();
        txtSocialId = new javax.swing.JLabel();
        lblSocialId = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        bgEditCustomer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Edit Customer");
        setMinimumSize(new java.awt.Dimension(400, 610));
        setName("EditCustomerFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkDeactive.setBackground(new java.awt.Color(255, 255, 255));
        chkDeactive.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        chkDeactive.setForeground(new java.awt.Color(30, 30, 30));
        chkDeactive.setText("Deactive");
        chkDeactive.setBorder(null);
        chkDeactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDeactiveActionPerformed(evt);
            }
        });
        getContentPane().add(chkDeactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        chkCustomerImage.setBackground(new java.awt.Color(255, 255, 255));
        chkCustomerImage.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        chkCustomerImage.setForeground(new java.awt.Color(30, 30, 30));
        chkCustomerImage.setText("Have a Image");
        chkCustomerImage.setBorder(null);
        chkCustomerImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCustomerImageActionPerformed(evt);
            }
        });
        getContentPane().add(chkCustomerImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        txtPhoneNumber.setBackground(new java.awt.Color(250, 250, 250));
        txtPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(30, 30, 30));
        txtPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPhoneNumber.setBorder(null);
        txtPhoneNumber.setMaximumSize(new java.awt.Dimension(220, 30));
        txtPhoneNumber.setMinimumSize(new java.awt.Dimension(220, 30));
        txtPhoneNumber.setPreferredSize(new java.awt.Dimension(220, 30));
        txtPhoneNumber.setSelectionColor(new java.awt.Color(119, 91, 200));
        getContentPane().add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 335, 180, 30));

        lblPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(30, 30, 30));
        lblPhoneNumber.setText("Phone Number:");
        getContentPane().add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txtAddress.setBackground(new java.awt.Color(250, 250, 250));
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(30, 30, 30));
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAddress.setBorder(null);
        txtAddress.setMaximumSize(new java.awt.Dimension(220, 30));
        txtAddress.setMinimumSize(new java.awt.Dimension(220, 30));
        txtAddress.setPreferredSize(new java.awt.Dimension(220, 30));
        txtAddress.setSelectionColor(new java.awt.Color(119, 91, 200));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 385, 230, 30));

        lblRegisteredDate.setBackground(new java.awt.Color(255, 255, 255));
        lblRegisteredDate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lblRegisteredDate.setForeground(new java.awt.Color(30, 30, 30));
        lblRegisteredDate.setText("Registered Date:");
        getContentPane().add(lblRegisteredDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        txtRegisteredDate.setBackground(new java.awt.Color(255, 255, 255));
        txtRegisteredDate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtRegisteredDate.setForeground(new java.awt.Color(30, 30, 30));
        getContentPane().add(txtRegisteredDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 285, 160, 30));

        lblAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(30, 30, 30));
        lblAddress.setText("Address:");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        lblDateRange.setBackground(new java.awt.Color(255, 255, 255));
        lblDateRange.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lblDateRange.setForeground(new java.awt.Color(30, 30, 30));
        lblDateRange.setText("Date Range:");
        getContentPane().add(lblDateRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txtDateRange.setBackground(new java.awt.Color(255, 255, 255));
        txtDateRange.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtDateRange.setForeground(new java.awt.Color(30, 30, 30));
        getContentPane().add(txtDateRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 235, 200, 30));

        txtSocialId.setBackground(new java.awt.Color(255, 255, 255));
        txtSocialId.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtSocialId.setForeground(new java.awt.Color(30, 30, 30));
        getContentPane().add(txtSocialId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 185, 200, 30));

        lblSocialId.setBackground(new java.awt.Color(255, 255, 255));
        lblSocialId.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lblSocialId.setForeground(new java.awt.Color(30, 30, 30));
        lblSocialId.setText("Social ID:");
        getContentPane().add(lblSocialId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        lblCustomerName.setBackground(new java.awt.Color(255, 255, 255));
        lblCustomerName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(30, 30, 30));
        lblCustomerName.setText("Customer:");
        getContentPane().add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtCustomerName.setBackground(new java.awt.Color(255, 255, 255));
        txtCustomerName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtCustomerName.setForeground(new java.awt.Color(30, 30, 30));
        getContentPane().add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 135, 200, 30));

        txtCustomerId.setBackground(new java.awt.Color(255, 255, 255));
        txtCustomerId.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtCustomerId.setForeground(new java.awt.Color(30, 30, 30));
        getContentPane().add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 85, 200, 30));

        lblCustomerId.setBackground(new java.awt.Color(255, 255, 255));
        lblCustomerId.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lblCustomerId.setForeground(new java.awt.Color(30, 30, 30));
        lblCustomerId.setText("Customer ID:");
        getContentPane().add(lblCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCancel.png"))); // NOI18N
        btnCancel.setBorder(null);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconSave.png"))); // NOI18N
        btnSave.setBorder(null);
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        bgEditCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pnlEditCustomer.png"))); // NOI18N
        getContentPane().add(bgEditCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconSaveHover.png")));
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconSave.png")));
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean isOk = true;
        String message = "";
        if (!Validation.phoneNumber(txtPhoneNumber.getText())) {
            isOk = false;
            message = message + "- Phone number must be 10+ digits.\n";
        }
        if (isOk == false) {
            JOptionPane.showMessageDialog(null, message, "Error list:", 0);
        } else {
            updateCustomer();
            JOptionPane.showMessageDialog(null, "Customer update successfully.", "Notification", 1);
            callHome();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCancelHover.png")));
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCancel.png")));
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        callHome();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void chkDeactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDeactiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDeactiveActionPerformed

    private void chkCustomerImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCustomerImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCustomerImageActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Redeem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Redeem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Redeem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Redeem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Redeem().setVisible(true);
//            }
//        });
//    }
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private ContractModel contractModel;
    private CustomerModel customerModel;
    private long redeemValid;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgEditCustomer;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkCustomerImage;
    private javax.swing.JCheckBox chkDeactive;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDateRange;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblRegisteredDate;
    private javax.swing.JLabel lblSocialId;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JLabel txtCustomerId;
    private javax.swing.JLabel txtCustomerName;
    private javax.swing.JLabel txtDateRange;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JLabel txtRegisteredDate;
    private javax.swing.JLabel txtSocialId;
    // End of variables declaration//GEN-END:variables
}
