/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.AssetModel;
import Model.ContractModel;
import Model.CustomerModel;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KhoiLeQuoc
 */
public class Home extends javax.swing.JFrame {

    CardLayout cardLayout;
    DefaultTableModel tableContract;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        Image favicon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/favicon.png"));
        this.setIconImage(favicon);
        cardLayout = (CardLayout) (pnlRight.getLayout());
        tableContract = (DefaultTableModel) tblContract.getModel();
        try {
            loadContract();
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public final void loadContract() throws Exception {
        ContractModel contractModel = new ContractModel();
        CustomerModel customerModel = new CustomerModel();
        AssetModel assetModel = new AssetModel();

        for (int i = 0; i < contractModel.getList().size(); i++) {
            int contractId = contractModel.getList().get(i).getContractId();
            String customerName = customerModel.getCustomerName(contractModel.getList().get(i).getContractId());
            String assetName = assetModel.getAssetName(contractModel.getList().get(i).getContractId());
            long totalLoanAmount = contractModel.getList().get(i).getTotalLoanAmount();
            String startDate = contractModel.getList().get(i).getStartDate();
            String endDate = contractModel.getList().get(i).getEndDate();
            long totalMoney = contractModel.getList().get(i).getTotalMoney();
            String status = "";
            if (contractModel.getList().get(i).getStatus() == 1) {
                status = "Đang cầm";
            } else if (contractModel.getList().get(i).getStatus() == 0) {
                status = "Đáo hạn";
            } else {
                status = "Không xác định";
            }

            tableContract.insertRow(tblContract.getRowCount(), new Object[]{
                contractId,
                customerName,
                assetName,
                totalLoanAmount,
                startDate,
                endDate,
                totalMoney,
                status
            });
            System.out.println(contractId + " | " + customerName + " | " + assetName + " | " + totalLoanAmount + " | " + startDate + " | " + endDate + " | " + totalMoney + " | " + status);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSplitPane = new javax.swing.JSplitPane();
        pnlLeft = new javax.swing.JPanel();
        btnBadDebts = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        btnEmployee = new javax.swing.JLabel();
        btnInvestment = new javax.swing.JLabel();
        btnStore = new javax.swing.JLabel();
        btnCustomer = new javax.swing.JLabel();
        btnPawnedOff = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JLabel();
        backgroundLeft = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        pnlCardDashboard = new javax.swing.JPanel();
        btnHowToUse = new javax.swing.JLabel();
        btnContact = new javax.swing.JLabel();
        btnAboutUs = new javax.swing.JLabel();
        bgDashboard = new javax.swing.JLabel();
        pnlCardPawnedOff = new javax.swing.JPanel();
        pnlScrollTable = new javax.swing.JScrollPane();
        tblContract = new javax.swing.JTable();
        btnNewContract = new javax.swing.JButton();
        btnExport = new javax.swing.JLabel();
        bgPawnedOff = new javax.swing.JLabel();
        pnlCardCustomer = new javax.swing.JPanel();
        pnlCardStore = new javax.swing.JPanel();
        pnlCardInvestment = new javax.swing.JPanel();
        pnlCardEmployee = new javax.swing.JPanel();
        pnlCardReport = new javax.swing.JPanel();
        pnlCardBadDebts = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pawnshoper");
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setName("home"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSplitPane.setDividerLocation(200);
        pnlSplitPane.setDividerSize(0);
        pnlSplitPane.setLastDividerLocation(200);
        pnlSplitPane.setMaximumSize(new java.awt.Dimension(1200, 700));
        pnlSplitPane.setMinimumSize(new java.awt.Dimension(1200, 700));
        pnlSplitPane.setPreferredSize(new java.awt.Dimension(1200, 700));

        pnlLeft.setMaximumSize(new java.awt.Dimension(200, 700));
        pnlLeft.setMinimumSize(new java.awt.Dimension(200, 700));
        pnlLeft.setPreferredSize(new java.awt.Dimension(200, 700));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBadDebts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconBadDept.png"))); // NOI18N
        btnBadDebts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBadDebts.setPreferredSize(new java.awt.Dimension(200, 40));
        btnBadDebts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBadDebtsMousePressed(evt);
            }
        });
        pnlLeft.add(btnBadDebts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconReport.png"))); // NOI18N
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.setPreferredSize(new java.awt.Dimension(200, 40));
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReportMousePressed(evt);
            }
        });
        pnlLeft.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconEmployee.png"))); // NOI18N
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployee.setPreferredSize(new java.awt.Dimension(200, 40));
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmployeeMousePressed(evt);
            }
        });
        pnlLeft.add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        btnInvestment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconInvestment.png"))); // NOI18N
        btnInvestment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInvestment.setPreferredSize(new java.awt.Dimension(200, 40));
        btnInvestment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInvestmentMousePressed(evt);
            }
        });
        pnlLeft.add(btnInvestment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        btnStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconStore.png"))); // NOI18N
        btnStore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStore.setPreferredSize(new java.awt.Dimension(200, 40));
        btnStore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStoreMousePressed(evt);
            }
        });
        pnlLeft.add(btnStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCustomer.png"))); // NOI18N
        btnCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomer.setPreferredSize(new java.awt.Dimension(200, 40));
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCustomerMousePressed(evt);
            }
        });
        pnlLeft.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        btnPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconPawn.png"))); // NOI18N
        btnPawnedOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPawnedOff.setPreferredSize(new java.awt.Dimension(200, 40));
        btnPawnedOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPawnedOffMousePressed(evt);
            }
        });
        pnlLeft.add(btnPawnedOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDashboardHover.png"))); // NOI18N
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setPreferredSize(new java.awt.Dimension(200, 40));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDashboardMousePressed(evt);
            }
        });
        pnlLeft.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        backgroundLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/panelLeft.png"))); // NOI18N
        pnlLeft.add(backgroundLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlSplitPane.setLeftComponent(pnlLeft);

        pnlRight.setMaximumSize(new java.awt.Dimension(1000, 700));
        pnlRight.setMinimumSize(new java.awt.Dimension(1000, 700));
        pnlRight.setLayout(new java.awt.CardLayout());

        pnlCardDashboard.setBackground(new java.awt.Color(153, 153, 255));
        pnlCardDashboard.setMaximumSize(new java.awt.Dimension(1000, 700));
        pnlCardDashboard.setMinimumSize(new java.awt.Dimension(1000, 700));
        pnlCardDashboard.setPreferredSize(new java.awt.Dimension(1000, 700));
        pnlCardDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHowToUse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHowToUse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHowToUseMousePressed(evt);
            }
        });
        pnlCardDashboard.add(btnHowToUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 635, 120, 30));

        btnContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnContactMousePressed(evt);
            }
        });
        pnlCardDashboard.add(btnContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 635, 120, 30));

        btnAboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAboutUsMousePressed(evt);
            }
        });
        pnlCardDashboard.add(btnAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 635, 120, 30));

        bgDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/panelRight.png"))); // NOI18N
        bgDashboard.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlCardDashboard.add(bgDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlRight.add(pnlCardDashboard, "pnlCardDashboard");

        pnlCardPawnedOff.setBackground(new java.awt.Color(0, 255, 102));
        pnlCardPawnedOff.setMaximumSize(new java.awt.Dimension(1000, 700));
        pnlCardPawnedOff.setMinimumSize(new java.awt.Dimension(1000, 700));
        pnlCardPawnedOff.setPreferredSize(new java.awt.Dimension(1000, 700));
        pnlCardPawnedOff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlScrollTable.setBackground(new java.awt.Color(255, 255, 255));
        pnlScrollTable.setBorder(null);
        pnlScrollTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnlScrollTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlScrollTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlScrollTable.setMaximumSize(new java.awt.Dimension(970, 530));
        pnlScrollTable.setMinimumSize(new java.awt.Dimension(970, 530));
        pnlScrollTable.setPreferredSize(new java.awt.Dimension(970, 530));

        tblContract.setBackground(new java.awt.Color(255, 255, 255));
        tblContract.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblContract.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Customer", "Asset", "Loan Amount", "Start Date", "End Date", "Total Money", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContract.setToolTipText("");
        tblContract.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblContract.setFocusable(false);
        tblContract.setGridColor(new java.awt.Color(255, 255, 255));
        tblContract.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblContract.setMaximumSize(new java.awt.Dimension(970, 530));
        tblContract.setMinimumSize(new java.awt.Dimension(970, 530));
        tblContract.setPreferredSize(new java.awt.Dimension(970, 530));
        tblContract.setRowHeight(25);
        tblContract.setSelectionBackground(new java.awt.Color(119, 91, 200));
        tblContract.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblContract.getTableHeader().setReorderingAllowed(false);
        pnlScrollTable.setViewportView(tblContract);
        if (tblContract.getColumnModel().getColumnCount() > 0) {
            tblContract.getColumnModel().getColumn(0).setMinWidth(10);
            tblContract.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblContract.getColumnModel().getColumn(0).setMaxWidth(80);
            tblContract.getColumnModel().getColumn(1).setMinWidth(100);
            tblContract.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblContract.getColumnModel().getColumn(1).setMaxWidth(400);
            tblContract.getColumnModel().getColumn(2).setMinWidth(100);
            tblContract.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblContract.getColumnModel().getColumn(2).setMaxWidth(400);
            tblContract.getColumnModel().getColumn(3).setMinWidth(100);
            tblContract.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblContract.getColumnModel().getColumn(3).setMaxWidth(200);
            tblContract.getColumnModel().getColumn(4).setMinWidth(100);
            tblContract.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblContract.getColumnModel().getColumn(4).setMaxWidth(200);
            tblContract.getColumnModel().getColumn(5).setMinWidth(100);
            tblContract.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblContract.getColumnModel().getColumn(5).setMaxWidth(200);
            tblContract.getColumnModel().getColumn(6).setMinWidth(100);
            tblContract.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblContract.getColumnModel().getColumn(6).setMaxWidth(200);
            tblContract.getColumnModel().getColumn(7).setResizable(false);
        }

        pnlCardPawnedOff.add(pnlScrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 970, 530));

        btnNewContract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconNewContact.png"))); // NOI18N
        btnNewContract.setBorder(null);
        btnNewContract.setBorderPainted(false);
        btnNewContract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewContract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewContractMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewContractMouseExited(evt);
            }
        });
        btnNewContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewContractActionPerformed(evt);
            }
        });
        pnlCardPawnedOff.add(btnNewContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconExportToExcel.png"))); // NOI18N
        btnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExportMouseExited(evt);
            }
        });
        pnlCardPawnedOff.add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        bgPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pnlPawnedOff.png"))); // NOI18N
        bgPawnedOff.setToolTipText("");
        pnlCardPawnedOff.add(bgPawnedOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlRight.add(pnlCardPawnedOff, "pnlCardPawnedOff");

        pnlCardCustomer.setBackground(new java.awt.Color(0, 0, 255));
        pnlCardCustomer.setMaximumSize(new java.awt.Dimension(1030, 700));
        pnlCardCustomer.setMinimumSize(new java.awt.Dimension(1030, 700));

        javax.swing.GroupLayout pnlCardCustomerLayout = new javax.swing.GroupLayout(pnlCardCustomer);
        pnlCardCustomer.setLayout(pnlCardCustomerLayout);
        pnlCardCustomerLayout.setHorizontalGroup(
            pnlCardCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        pnlCardCustomerLayout.setVerticalGroup(
            pnlCardCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pnlRight.add(pnlCardCustomer, "pnlCardCustomer");

        pnlCardStore.setBackground(new java.awt.Color(51, 102, 255));
        pnlCardStore.setMaximumSize(new java.awt.Dimension(1030, 700));
        pnlCardStore.setMinimumSize(new java.awt.Dimension(1030, 700));

        javax.swing.GroupLayout pnlCardStoreLayout = new javax.swing.GroupLayout(pnlCardStore);
        pnlCardStore.setLayout(pnlCardStoreLayout);
        pnlCardStoreLayout.setHorizontalGroup(
            pnlCardStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        pnlCardStoreLayout.setVerticalGroup(
            pnlCardStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pnlRight.add(pnlCardStore, "pnlCardStore");

        pnlCardInvestment.setBackground(new java.awt.Color(153, 153, 255));
        pnlCardInvestment.setMaximumSize(new java.awt.Dimension(1030, 700));
        pnlCardInvestment.setMinimumSize(new java.awt.Dimension(1030, 700));

        javax.swing.GroupLayout pnlCardInvestmentLayout = new javax.swing.GroupLayout(pnlCardInvestment);
        pnlCardInvestment.setLayout(pnlCardInvestmentLayout);
        pnlCardInvestmentLayout.setHorizontalGroup(
            pnlCardInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        pnlCardInvestmentLayout.setVerticalGroup(
            pnlCardInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pnlRight.add(pnlCardInvestment, "pnlCardInvestment");

        pnlCardEmployee.setBackground(new java.awt.Color(0, 204, 153));
        pnlCardEmployee.setMaximumSize(new java.awt.Dimension(1030, 700));
        pnlCardEmployee.setMinimumSize(new java.awt.Dimension(1030, 700));

        javax.swing.GroupLayout pnlCardEmployeeLayout = new javax.swing.GroupLayout(pnlCardEmployee);
        pnlCardEmployee.setLayout(pnlCardEmployeeLayout);
        pnlCardEmployeeLayout.setHorizontalGroup(
            pnlCardEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        pnlCardEmployeeLayout.setVerticalGroup(
            pnlCardEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pnlRight.add(pnlCardEmployee, "pnlCardEmployee");

        pnlCardReport.setBackground(new java.awt.Color(102, 0, 153));
        pnlCardReport.setMaximumSize(new java.awt.Dimension(1030, 700));
        pnlCardReport.setMinimumSize(new java.awt.Dimension(1030, 700));

        javax.swing.GroupLayout pnlCardReportLayout = new javax.swing.GroupLayout(pnlCardReport);
        pnlCardReport.setLayout(pnlCardReportLayout);
        pnlCardReportLayout.setHorizontalGroup(
            pnlCardReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        pnlCardReportLayout.setVerticalGroup(
            pnlCardReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pnlRight.add(pnlCardReport, "pnlCardReport");

        pnlCardBadDebts.setBackground(new java.awt.Color(204, 204, 255));
        pnlCardBadDebts.setMaximumSize(new java.awt.Dimension(1030, 700));
        pnlCardBadDebts.setMinimumSize(new java.awt.Dimension(1030, 700));

        javax.swing.GroupLayout pnlCardBadDebtsLayout = new javax.swing.GroupLayout(pnlCardBadDebts);
        pnlCardBadDebts.setLayout(pnlCardBadDebtsLayout);
        pnlCardBadDebtsLayout.setHorizontalGroup(
            pnlCardBadDebtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        pnlCardBadDebtsLayout.setVerticalGroup(
            pnlCardBadDebtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pnlRight.add(pnlCardBadDebts, "pnlCardBadDebts");

        pnlSplitPane.setRightComponent(pnlRight);

        getContentPane().add(pnlSplitPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMousePressed
        cardLayout.show(pnlRight, "pnlCardDashboard");
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDashboardHover.png")));
        btnPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconPawn.png")));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCustomer.png")));
        btnStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconStore.png")));
        btnInvestment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconInvestment.png")));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconEmployee.png")));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconReport.png")));
        btnBadDebts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconBadDept.png")));
    }//GEN-LAST:event_btnDashboardMousePressed

    private void btnPawnedOffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPawnedOffMousePressed
        cardLayout.show(pnlRight, "pnlCardPawnedOff");
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDashboard.png")));
        btnPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconPawnHover.png")));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCustomer.png")));
        btnStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconStore.png")));
        btnInvestment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconInvestment.png")));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconEmployee.png")));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconReport.png")));
        btnBadDebts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconBadDept.png")));
    }//GEN-LAST:event_btnPawnedOffMousePressed

    private void btnCustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMousePressed
        cardLayout.show(pnlRight, "pnlCardCustomer");
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDashboard.png")));
        btnPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconPawn.png")));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCustomerHover.png")));
        btnStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconStore.png")));
        btnInvestment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconInvestment.png")));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconEmployee.png")));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconReport.png")));
        btnBadDebts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconBadDept.png")));
    }//GEN-LAST:event_btnCustomerMousePressed

    private void btnStoreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStoreMousePressed
        cardLayout.show(pnlRight, "pnlCardStore");
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDashboard.png")));
        btnPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconPawn.png")));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCustomer.png")));
        btnStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconStoreHover.png")));
        btnInvestment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconInvestment.png")));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconEmployee.png")));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconReport.png")));
        btnBadDebts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconBadDept.png")));
    }//GEN-LAST:event_btnStoreMousePressed

    private void btnInvestmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvestmentMousePressed
        cardLayout.show(pnlRight, "pnlCardInvestment");
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDashboard.png")));
        btnPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconPawn.png")));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCustomer.png")));
        btnStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconStore.png")));
        btnInvestment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconInvestmentHover.png")));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconEmployee.png")));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconReport.png")));
        btnBadDebts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconBadDept.png")));
    }//GEN-LAST:event_btnInvestmentMousePressed

    private void btnEmployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMousePressed
        cardLayout.show(pnlRight, "pnlCardEmployee");
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDashboard.png")));
        btnPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconPawn.png")));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCustomer.png")));
        btnStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconStore.png")));
        btnInvestment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconInvestment.png")));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconEmployeeHover.png")));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconReport.png")));
        btnBadDebts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconBadDept.png")));
    }//GEN-LAST:event_btnEmployeeMousePressed

    private void btnReportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMousePressed
        cardLayout.show(pnlRight, "pnlCardReport");
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDashboard.png")));
        btnPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconPawn.png")));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCustomer.png")));
        btnStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconStore.png")));
        btnInvestment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconInvestment.png")));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconEmployee.png")));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconReportHover.png")));
        btnBadDebts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconBadDept.png")));
    }//GEN-LAST:event_btnReportMousePressed

    private void btnBadDebtsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBadDebtsMousePressed
        cardLayout.show(pnlRight, "pnlCardBadDebts");
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDashboard.png")));
        btnPawnedOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconPawn.png")));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCustomer.png")));
        btnStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconStore.png")));
        btnInvestment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconInvestment.png")));
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconEmployee.png")));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconReport.png")));
        btnBadDebts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconBadDeptHover.png")));
    }//GEN-LAST:event_btnBadDebtsMousePressed

    private void btnAboutUsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutUsMousePressed
        btnAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about.png")));
        btnContact.setIcon(null);
        btnHowToUse.setIcon(null);
    }//GEN-LAST:event_btnAboutUsMousePressed

    private void btnContactMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactMousePressed
        btnAboutUs.setIcon(null);
        btnContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contact.png")));
        btnHowToUse.setIcon(null);
    }//GEN-LAST:event_btnContactMousePressed

    private void btnHowToUseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHowToUseMousePressed
        btnAboutUs.setIcon(null);
        btnContact.setIcon(null);
        btnHowToUse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/howtouse.png")));
    }//GEN-LAST:event_btnHowToUseMousePressed

    private void btnExportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportMouseEntered
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconExportToExcelHover.png")));
    }//GEN-LAST:event_btnExportMouseEntered

    private void btnExportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportMouseExited
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconExportToExcel.png")));
    }//GEN-LAST:event_btnExportMouseExited

    private void btnNewContractMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewContractMouseEntered
        btnNewContract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconNewContactHover.png")));
    }//GEN-LAST:event_btnNewContractMouseEntered

    private void btnNewContractMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewContractMouseExited
        btnNewContract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconNewContact.png")));
    }//GEN-LAST:event_btnNewContractMouseExited

    private void btnNewContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewContractActionPerformed
        try {
            NewContract newContract = new NewContract();
            newContract.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewContractActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLeft;
    private javax.swing.JLabel bgDashboard;
    private javax.swing.JLabel bgPawnedOff;
    private javax.swing.JLabel btnAboutUs;
    private javax.swing.JLabel btnBadDebts;
    private javax.swing.JLabel btnContact;
    private javax.swing.JLabel btnCustomer;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnEmployee;
    private javax.swing.JLabel btnExport;
    private javax.swing.JLabel btnHowToUse;
    private javax.swing.JLabel btnInvestment;
    private javax.swing.JButton btnNewContract;
    private javax.swing.JLabel btnPawnedOff;
    private javax.swing.JLabel btnReport;
    private javax.swing.JLabel btnStore;
    private javax.swing.JPanel pnlCardBadDebts;
    private javax.swing.JPanel pnlCardCustomer;
    private javax.swing.JPanel pnlCardDashboard;
    private javax.swing.JPanel pnlCardEmployee;
    private javax.swing.JPanel pnlCardInvestment;
    private javax.swing.JPanel pnlCardPawnedOff;
    private javax.swing.JPanel pnlCardReport;
    private javax.swing.JPanel pnlCardStore;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JScrollPane pnlScrollTable;
    private javax.swing.JSplitPane pnlSplitPane;
    private javax.swing.JTable tblContract;
    // End of variables declaration//GEN-END:variables

}
